### ISSUE TITLE
Update broken on Fedora 40

### ISSUE THREAD

**Issue by mixmastamyk** [paolostivanin/OTPClient#389]
```
error: Verifying a signature using certificate B2437D2BAFEBA93384F8F25FFB161AA97C614E92 (home:polslinux OBS Project <home:polslinux@build.opensuse.org>):
  1. Certificate FB161AA97C614E92 invalid: certificate is not alive
      because: The primary key is not live
      because: Expired on 2024-11-18T03:25:17Z
  2. Key FB161AA97C614E92 invalid: key is not alive
      because: The primary key is not live
      because: Expired on 2024-11-18T03:25:17Z
The GPG keys listed for the "created by dnf config-manager from https://download.opensuse.org/repositories/home:/polslinux:/otpclient/Fedora_40/" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.. Failing package is: libcotp3-3.1.0-1.25.x86_64
```

Because of this I can no longer update my machine.  Think I will have to uninstall this program to proceed.  :-(

I tried updating the key using the commands from the wiki, but it did not appear to help.

**Comment by paolostivanin** [comment]
hello! Sorry, I'm not really familiar with Fedora. This may work:

```
sudo rpm --import https://download.opensuse.org/repositories/home:/polslinux:/otpclient/Fedora_40/repodata/repomd.xml.key
sudo dnf clean all
sudo dnf makecache
```

let me know.

**Comment by mixmastamyk** [comment]
Still get:

```
...
The primary key is not live
      because: Expired on 2024-11-18 03:25:17Z
...
```

**Comment by paolostivanin** [comment]
Do you still get this error? If yes, please contact someone over at https://openbuildservice.org/support/ . Unfortunately, there's nothing I can do on my side :(

**Comment by satsuki-chan** [comment]
Hello @paolostivanin ,

Sadly, I also have the same issue as @mixmastamyk with my repository in **Fedora 40**:
```
====================================================================================================================================
 Package                   Architecture           Version                       Repository                                     Size
====================================================================================================================================
Upgrading:
 libcotp3                  x86_64                 3.1.0-1.44                    polslinux_otpclient_Fedora_40                  17 k
 otpclient                 x86_64                 4.0.2-1.74                    polslinux_otpclient_Fedora_40                 120 k

Transaction Summary
====================================================================================================================================
Upgrade  2 Packages

Total download size: 137 k
Downloading Packages:
(1/2): libcotp3-3.1.0-1.44.x86_64.rpm                                                                23 kB/s |  17 kB     00:00    
(2/2): otpclient-4.0.2-1.74.x86_64.rpm                                                              128 kB/s | 120 kB     00:00    
------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                               145 kB/s | 137 kB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
RPM: error: Verifying a signature using certificate B2437D2BAFEBA93384F8F25FFB161AA97C614E92 (home:polslinux OBS Project <home:polslinux@build.opensuse.org>):
RPM:   1. Certificate FB161AA97C614E92 invalid: certificate is not alive
RPM:       because: The primary key is not live
RPM:       because: Expired on 2024-11-18T03:25:17Z
RPM:   2. Key FB161AA97C614E92 invalid: key is not alive
RPM:       because: The primary key is not live
RPM:       because: Expired on 2024-11-18T03:25:17Z
RPM: error: Verifying a signature using certificate B2437D2BAFEBA93384F8F25FFB161AA97C614E92 (home:polslinux OBS Project <home:polslinux@build.opensuse.org>):
RPM:   1. Certificate FB161AA97C614E92 invalid: certificate is not alive
RPM:       because: The primary key is not live
RPM:       because: Expired on 2024-11-18T03:25:17Z
RPM:   2. Key FB161AA97C614E92 invalid: key is not alive
RPM:       because: The primary key is not live
RPM:       because: Expired on 2024-11-18T03:25:17Z
RPM: error: Verifying a signature using certificate B2437D2BAFEBA93384F8F25FFB161AA97C614E92 (home:polslinux OBS Project <home:polslinux@build.opensuse.org>):
RPM:   1. Certificate FB161AA97C614E92 invalid: certificate is not alive
RPM:       because: The primary key is not live
RPM:       because: Expired on 2024-11-18T03:25:17Z
RPM:   2. Key FB161AA97C614E92 invalid: key is not alive
RPM:       because: The primary key is not live
RPM:       because: Expired on 2024-11-18T03:25:17Z
RPM: error: Verifying a signature using certificate B2437D2BAFEBA93384F8F25FFB161AA97C614E92 (home:polslinux OBS Project <home:polslinux@build.opensuse.org>):
RPM:   1. Certificate FB161AA97C614E92 invalid: certificate is not alive
RPM:       because: The primary key is not live
RPM:       because: Expired on 2024-11-18T03:25:17Z
RPM:   2. Key FB161AA97C614E92 invalid: key is not alive
RPM:       because: The primary key is not live
RPM:       because: Expired on 2024-11-18T03:25:17Z
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction test error:
  package libcotp3-3.1.0-1.44.x86_64 does not verify: Header V3 RSA/SHA256 Signature, key ID 7c614e92: NOTTRUSTED
  package otpclient-4.0.2-1.74.x86_64 does not verify: Header V3 RSA/SHA256 Signature, key ID 7c614e92: NOTTRUSTED
```

As I understand it, the problem is that the checksums of all the files in the repository were not updated with the new certificate:
`https://download.opensuse.org/repositories/home:/polslinux:/otpclient/Fedora_40/repodata/4bbf2a681557a6901b32f0b8fe01ced2ba42ee959245d3a5dfbcbfe88b1a397b-primary.xml.gz`

Hence the error that the verification process keeps asking for the previous (expired) certificate.

**Comment by paolostivanin** [comment]
Thanks for the update! I'll write to the OBS team because I have no way of controlling the signing part.
Unfortunately, I cannot force a rebuild with a specific key.

**Comment by paolostivanin** [comment]
@satsuki-chan is it sill the case? I can see that all repodata is updated and the key is actually good:

```
 $ gpg --show-keys repomd.xml.key 
gpg: WARNING: unsafe permissions on homedir '/home/pstivanin/.gnupg'
pub   rsa2048 2018-05-20 [SC] [expires: 2027-01-13]
      B2437D2BAFEBA93384F8F25FFB161AA97C614E92
uid                      home:polslinux OBS Project <home:polslinux@build.opensuse.org>
```

**Comment by paolostivanin** [comment]
FYI https://bugzilla.opensuse.org/show_bug.cgi?id=1235148

**Comment by paolostivanin** [comment]
the key has been extended! It will take 24/48h for it to work though

**Comment by paolostivanin** [comment]
@mixmastamyk @satsuki-chan 

```
libcotp-3.1.0-1.49
otpclient-4.0.2-1.80
```

are out and should fix the issue :smile:

**Comment by mixmastamyk** [comment]
Still doesn't work.  This shouldn't be so hard. 

    Public key for otpclient-4.0.2-1.80.x86_64.rpm is not trusted. Failing package is: otpclient-4.0.2-1.80.x86_64

**Comment by paolostivanin** [comment]
I guess you need to import the new key. Dunno why dnf is not prompting to add it to be honest.

You can find the new key here: https://build.opensuse.org/projects/home:polslinux:otpclient/signing_keys/download?kind=gpg

**Comment by mixmastamyk** [comment]
Ok, I got it to work (finally)!  Using tips on this page:

https://www.redhat.com/en/blog/rpm-gpg-verify-packages

Editing the /etc/ .repo files didn't seem to fix it, but looking at:

    ⏵ rpm -qa gpg-pubkey\*

I decided to remove them all, one at a time:

    ⏵ sudo rpm -e gpg-pubkey-...-...

Then I ran the commands below and was asked to import new keys, then it was installed:

    ⏵ sudo dnf upgrade --refresh 
    ⏵ sudo dnf install otpclient
